spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


mybatis-plus:
  mapper-locations: classpath:mapper/user/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



jwt:
  key: "mySecrtHiHiHi"
  expiration: 604800000  #60*60*24*1000 => 1天
  tokenHeader: Authorization
  tokenHead: Bearer
